arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - hi
  - bn
  - ta
  - te
  - as
  - gu
  - pa
  - kn
  - ml
  - mr
  - ur
  - ne
  - fr
  - de
  - zh
