name: tourist_safety_app
description: "A safety monitoring app for tourists with real-time tracking and emergency alerts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_maps_flutter: ^2.5.3
  flutter_blue_plus: ^1.31.5
  geolocator: ^10.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  mapbox_maps_flutter: 2.10.0
  cloud_firestore: ^4.15.8
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.68.0
  logging: ^1.1.0
  uuid: ^4.3.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - .env
    
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
