// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrZxcIuSTxiypITOlnesoLVcXl_iH_QY',
    appId: '1:1041906458754:web:7537d98133df2c8b59d49b',
    messagingSenderId: '1041906458754',
    projectId: 'tourist-safety-app-7791d',
    authDomain: 'tourist-safety-app-7791d.firebaseapp.com',
    storageBucket: 'tourist-safety-app-7791d.firebasestorage.app',
    measurementId: 'G-D3060FS5B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kV8ErZ9BlkLU5dXGwLpTWwI4sY6crD8',
    appId: '1:1041906458754:android:12f4e0b631a6bc3459d49b',
    messagingSenderId: '1041906458754',
    projectId: 'tourist-safety-app-7791d',
    storageBucket: 'tourist-safety-app-7791d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfmEqfEvi23jbhOZq1eiyYzfVM1PBNBAs',
    appId: '1:1041906458754:ios:ea876a542b6e8d8e59d49b',
    messagingSenderId: '1041906458754',
    projectId: 'tourist-safety-app-7791d',
    storageBucket: 'tourist-safety-app-7791d.firebasestorage.app',
    iosBundleId: 'com.smarttourist.touristSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfmEqfEvi23jbhOZq1eiyYzfVM1PBNBAs',
    appId: '1:1041906458754:ios:ea876a542b6e8d8e59d49b',
    messagingSenderId: '1041906458754',
    projectId: 'tourist-safety-app-7791d',
    storageBucket: 'tourist-safety-app-7791d.firebasestorage.app',
    iosBundleId: 'com.smarttourist.touristSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXrZxcIuSTxiypITOlnesoLVcXl_iH_QY',
    appId: '1:1041906458754:web:e21a564e1144a83f59d49b',
    messagingSenderId: '1041906458754',
    projectId: 'tourist-safety-app-7791d',
    authDomain: 'tourist-safety-app-7791d.firebaseapp.com',
    storageBucket: 'tourist-safety-app-7791d.firebasestorage.app',
    measurementId: 'G-GMQHGCKQ3C',
  );
}
